server:
  port: 8080
spring:
  profiles:
    active: usage_message
  data:
    mongodb:
#      host: localhost
#      port: 27017
#      uri: mongodb://user:secret@mongo1.example.com:12345,mongo2.example.com:23456/test
      uri: mongodb://localhost:27017/blog
      grid-fs-database: images
logging:
  level:
    org: DEBUG
tutorial:
  client:
    duration: 10000